# Generated by Django 5.1.7 on 2025-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                choices=[
                    ("Sydney", "Sydney"),
                    ("Melbourne", "Melbourne"),
                    ("Brisbane", "Brisbane"),
                    ("Adelaide", "Adelaide"),
                    ("Perth", "Perth"),
                    ("Hobart", "Hobart"),
                    ("Darwin", "Darwin"),
                    ("Canberra", "Canberra"),
                ],
                max_length=255,
            ),
        ),
    ]
