# Generated by Django 5.1.7 on 2025-04-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="location",
            new_name="city",
        ),
    ]
